version: '3.1'

services:

  snippetboxdb:
    image: postgres
    container_name: snippetboxdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: passwordhere
    volumes:
      - /var/lib/snippetboxdb

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: snippetboxpgadmin
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:5050"